// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function IsDowntime() {
  return window['go']['server']['Client']['IsDowntime']();
}

export function SendFileHandler(arg1) {
  return window['go']['server']['Client']['SendFileHandler'](arg1);
}

export function StartContext(arg1) {
  return window['go']['server']['Client']['StartContext'](arg1);
}

export function ToggleDowntime(arg1) {
  return window['go']['server']['Client']['ToggleDowntime'](arg1);
}
