// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {context} from '../models';

export function SendFile(arg1:string,arg2:boolean,arg3:Array<string>):Promise<string>;

export function StartContext(arg1:context.Context):Promise<void>;
