// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {server} from '../models';
import {context} from '../models';

export function SendFile(arg1:server.FileServerInfo):Promise<string>;

export function StartContext(arg1:context.Context):Promise<void>;
