// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function SendFile(arg1, arg2, arg3) {
  return window['go']['server']['FileServer']['SendFile'](arg1, arg2, arg3);
}

export function StartContext(arg1) {
  return window['go']['server']['FileServer']['StartContext'](arg1);
}
