// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function IsDowntime() {
  return window['go']['server']['Server']['IsDowntime']();
}

export function ReceiveFileHandler() {
  return window['go']['server']['Server']['ReceiveFileHandler']();
}

export function StartContext(arg1) {
  return window['go']['server']['Server']['StartContext'](arg1);
}

export function StopServerHandler() {
  return window['go']['server']['Server']['StopServerHandler']();
}

export function ToggleDowntime(arg1) {
  return window['go']['server']['Server']['ToggleDowntime'](arg1);
}
