// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {context} from '../models';

export function IsDowntime():Promise<boolean>;

export function ReceiveFileHandler():Promise<string>;

export function StartContext(arg1:context.Context):Promise<void>;

export function StopServerHandler():Promise<void>;

export function ToggleDowntime(arg1:boolean):Promise<void>;
